import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: "category",
      label: "Getting Started",
      items: ["intro", "configuration-and-state"],
    },
    {
      type: "category",
      label: "CLI Reference",
      items: ["cli", "init", "project", "term", "translation", "export"],
    },
    {
      type: "category",
      label: "SDK",
      items: [
        "sdk",
        {
          type: "category",
          label: "SDK TypeScript Reference",
          items: [{ type: "autogenerated", dirName: "sdk-reference" }],
        },
      ],
    },
  ],
};

export default sidebars;
